### ISSUE TITLE
Update Semgus-Java dependency to v1.1.0

### ISSUE THREAD

**Issue by ngsankha** [SemGuS-git/Semgus-Messy#1]
Hi,

I want to try out the Messy tool on my local machine. Is there a way to build this code directly from the repo without building in the artifact VM? If so, can you share the instructions.

Thanks!

**Comment by ngsankha** [comment]
Running `sbt assembly` results in the following error:

```
[info] welcome to sbt 1.6.2 (Homebrew Java 20.0.1)
[info] loading settings for project semgus-messy-build from plugins.sbt ...
[info] loading project definition from /Users/sankha/projects/Semgus-Messy/project
[info] loading settings for project semgus-messy from build.sbt ...
[info] set current project to Messy (in build file:/Users/sankha/projects/Semgus-Messy/)
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.SemGuS-git:Semgus-Java:1.0.2
[error]   Not found
[error]   Not found
[error]   not found: /Users/sankha/.ivy2/localcom.github.SemGuS-git/Semgus-Java/1.0.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/SemGuS-git/Semgus-Java/1.0.2/Semgus-Java-1.0.2.pom
[error]   not found: https://jitpack.io/com/github/SemGuS-git/Semgus-Java/1.0.2/Semgus-Java-1.0.2.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:345)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:314)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3690)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1623)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.github.SemGuS-git:Semgus-Java:1.0.2
[error]   Not found
[error]   Not found
[error]   not found: /Users/sankha/.ivy2/localcom.github.SemGuS-git/Semgus-Java/1.0.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/SemGuS-git/Semgus-Java/1.0.2/Semgus-Java-1.0.2.pom
[error]   not found: https://jitpack.io/com/github/SemGuS-git/Semgus-Java/1.0.2/Semgus-Java-1.0.2.pom
[error] Total time: 0 s, completed May 22, 2023, 6:17:47 PM
```

**Comment by ngsankha** [comment]
Updating the Semgus-Java version in build.sbt to "1.1.0" fixed the problem. I can open a PR if this is the right fix.

**Comment by kjcjohnson** [comment]
Apparently Semgus-Java v1.0.2 was targeting Java 16, which has EOL for quite some time. I would guess JitPack removed support for it. Updating to v1.1.0 is the right call, I'm just not sure if it's compatible - a lot changed in that version.

@kjw227 - have you looked into using Semgus-Java v1.1.0 with Messy?

**Comment by ngsankha** [comment]
@kjcjohnson yes, using Semgus-Java v1.1.0 in Messy fails with this exception on a JSON files (generated with the latest release of the SemGuS parser):

```
[info] welcome to sbt 1.6.2 (Homebrew Java 20.0.1)
[info] loading settings for project semgus-messy-build from plugins.sbt ...
[info] loading project definition from /Users/sankha/projects/Semgus-Messy/project
[info] loading settings for project semgus-messy from build.sbt ...
[info] set current project to Messy (in build file:/Users/sankha/projects/Semgus-Messy/)
[info] running Main --infile test.json
Translating test.json to an SMT file
[error] ExternalParseException: Unexpected event supplied by external JSON parser
[error] 	at semgusJava.package$.translateEvent(package.scala:117)
[error] 	at semgusJava.package$.$anonfun$translate2Semgus$1(package.scala:121)
[error] 	at scala.collection.immutable.List.map(List.scala:250)
[error] 	at semgusJava.package$.translate2Semgus(package.scala:121)
[error] 	at semgusJava.package$.JSON2Semgus(package.scala:123)
[error] 	at Main$.main(Main.scala:24)
[error] 	at Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) ExternalParseException: Unexpected event supplied by external JSON parser
[error] Total time: 1 s, completed May 22, 2023, 6:35:00 PM
```

**Comment by kjcjohnson** [comment]
As a workaround, try passing the `--no-function-events` flag to the SemGuS parser. That flag will disable the new events supported by v1.1.0 of SemGuS Java.

**Comment by ngsankha** [comment]
Thanks! `--no-function-events` option works with Messy.
